### ISSUE TITLE
Pon los tres de golpe y evitas duplicidad

### ISSUE THREAD

**Issue by lmagarin** [Javierfs94/Reentrega-Examen-jQuery#3]
https://github.com/Javierfs94/Reentrega-Examen-jQuery/blob/c5a5164719d0edcba4a4ebf0307c54cca1971877/js/main.js#L29

**Comment by Javierfs94** [comment]
No entiendo como podría poner los 3 ahí

**Comment by lmagarin** [comment]
```
$(`
            <p>Lourdes</p>
            <p>Magarín</p>
            <p>Corvillo</p>   
            `)
```

**Comment by Javierfs94** [comment]
¡Ahh! Era una tontería. Ahora entiendo también como queda su nombre y apellidos bien ordenado, mientras que el mío está al revés. ¡Muchas gracias! Ahora hago la modificación correspondiente :)
